language: node_js
notifications:
  email: false
node_js:
  - '13'
  - '12'
  - '11'
  - '10'
  - '9'
  - '8'
before_script:
  - yarn build
script:
  - yarn test
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npx semantic-release
